### ISSUE TITLE
React example: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by joshlory** [RaspberryPiFoundation/blockly-samples#11]
Repro steps:
1. Load the react demo.
2. Drag in a custom field.
3. Open the field, then close the field.

![repro](https://user-images.githubusercontent.com/413693/66671566-27edb600-ec11-11e9-9c42-57d6e993e4a5.gif)

**Comment by samelhusseini** [comment]
This issue has been fixed in the upcoming release. Release should be on npm next week.
