### ISSUE TITLE
Plugin template

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#156]
Files and folders needed for a plugin template:
- `eslintrc` (unless we move it up a level)
- `README`
- `package.json`
- `src/`
- `test/`
- `test/playground.html`
- `test/multi_playground.html`
- `webpack.config.js`

**Comment by rachel-fenichel** [comment]
After discussion, `eslintrc` is not needed because we're moving it up a level to `packages/plugins`

**Comment by samelhusseini** [comment]
``webpack.config.js`` is also no longer needed if ``@blockly/scripts`` is used.
