### ISSUE TITLE
Create easy way to test plugins

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#173]
**Is your feature request related to a problem? Please describe.**
Testing all of the plugins with the current blockly version on develop would take a significant amount of time. 

**Describe the solution you'd like**
A script and process that will make testing the blockly plugins a faster process than it currently is. This will probably include an easy way to link all the plugins to the current blockly version for testing. 

**Describe alternatives you've considered**
Not testing until after we release.

**Additional context**

**Comment by rachel-fenichel** [comment]
@alschmiedt is this fixed or superseded by more specific issues?
We now have the gh-pages site to make it easy to open all of them at once, and there's an issue for linking to beta.

**Comment by alschmiedt** [comment]
Yup, this is covered by #505
