### ISSUE TITLE
Plugin restructuring v3000

### ISSUE THREAD

**Issue by samelhusseini** [RaspberryPiFoundation/blockly-samples#209]
- [x] Move packages around
- [x] Update their package.json
- [x] Update READMEs
- [x] Republish all plugins
- [x] Update templates
- [x] Updating issue templates (Question about what the feature request it is about)
- [x] Move modern theme into a plugin
- [x] Add browser support in package.json
- [ ] Move screenshot to devtools
- [x] Typescript template?

**Comment by rachel-fenichel** [comment]
- [ ] Add plugin usage to framework integration examples

**Comment by rachel-fenichel** [comment]
I'll update issue templates today.

**Comment by samelhusseini** [comment]
https://github.com/google/blockly-samples/pulls and https://github.com/google/blockly-samples/pull/228 for Typescript support.

**Comment by samelhusseini** [comment]
https://github.com/google/blockly-samples/issues/234 tracking eslint changes

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly-samples/issues/245 tracks the last item, screenshot downloading in dev-tools.
