### ISSUE TITLE
Test blocks and test block toolbox in devtools

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#210]
Move the test blocks from the playground, and the test block toolbox, into devtools.

Why: they're useful for testing all plugins, not just code in core.

We can still use them in the core playground with unpkg and a script tag.

**Comment by rachel-fenichel** [comment]
Marking as internal so the Blockly team can coordinate changes in the core Blockly playground as well.

**Comment by samelhusseini** [comment]
Test blocks have been moved, leaving this open to track adding the test blocks toolbox to the default set of toolboxes present in the playground. We shall hold off on doing so before we finalize the JSON toolbox spec in the next release
