### ISSUE TITLE
Bump block-plus-minus Blockly Dependency (post next release)

### ISSUE THREAD

**Issue by BeksOmega** [RaspberryPiFoundation/blockly-samples#219]
I just remembered that the blockly dependency for the block-plus-minus package will need to be bumped after the next release because it relies on https://github.com/google/blockly/pull/3814 for the procedures to work properly.

Maybe it can be bumped ahead of time? Not sure.

Just wanted to put up an issue to make sure this doesn't get lost!

**Comment by samelhusseini** [comment]
Thanks for pointing that out @BeksOmega. The package has not been published and since it depends on the next release, we’ll wait till that happens before we publish it.

Let’s use this issue to track that.

**Comment by alschmiedt** [comment]
Blockly dependency for block-plus-minus has been set to >=3.20202625.1 in #315
