### ISSUE TITLE
Codelab to write a theme plugin

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#224]
**Category**

Codelabs

**Component**

Title: Create a Custom Theme

**Describe the solution you'd like**
A codelab in which the user creates a super spooky halloween theme for Blockly.

Sections:
- Codelab Overview
  - What you'll learn
  - What you'll build
- Setup
- Define Theme
- ???

**Describe alternatives you've considered**

Leave the documentation as-is.

**Additional context**

https://developers.google.com/blockly/guides/configure/web/themes

**Comment by rachel-fenichel** [comment]
@alschmiedt for ideas on what sections this would need.

**Comment by alschmiedt** [comment]
- Add Css (to show adding theme specific CSS)
- Testing? (Could point out some tools to test contrast is at acceptable level)
