### ISSUE TITLE
Where is the prompt. Js file used?What does it do?

### ISSUE THREAD

**Issue by gscwj** [RaspberryPiFoundation/blockly-samples#231]
Where is the prompt. Js file used?What does it do?

**Comment by samelhusseini** [comment]
I assume you're referring to this file: https://github.com/google/blockly-samples/blob/master/examples/blockly-vue/src/prompt.js

If so, it's used by the Vue example [here](https://github.com/google/blockly-samples/blob/master/examples/blockly-vue/src/App.vue#L63) to show how to change Blockly's prompt behaviour to use a custom modal. In this case, it's ``sweetalert2``.
