### ISSUE TITLE
Make blockly div in all templates bigger

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#232]
**Category**
Templates

**Component**

All templates

**Describe the bug**
Index.html currently contains this:

```
<body>
  <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
  <script src="../build/test_bundle.js"></script>
</body>
```

It should be bigger (800x800?) to make it easier to have more than a few blocks visible at a time, and so that widgets don't hit the edge of the workspace so easily.

**Comment by samelhusseini** [comment]
Makes sense, although lets hold of on doing that until we figure out what the "playground" is going to look like. I'd much rather not have the same thing (index.html) configured in all of these plugins. We have a central script runner, it should be able to host a playground if one doesn't exist.
