### ISSUE TITLE
Add a Pull request template

### ISSUE THREAD

**Issue by samelhusseini** [RaspberryPiFoundation/blockly-samples#239]
Add a Pull request template.

What do we want in there?
- [ ]  Plugin / Example / Code lab
- [ ] ...
- [ ] ...

**Comment by BeksOmega** [comment]
Hm I wish github had better support for [multiple PR templates](https://github.community/t5/How-to-use-Git-and-GitHub/Multiple-Pull-Request-Templates/td-p/20909). They work, but there's no nice UI for them. You have to pass browser parameters manually :/

Anyway, what about:

* Type (codelab / example / plugin)
* Issue Number
* Description
* Testing
* Additional Info

Testing might be a weird one, but I figure that even codelabs and examples will need some manual testing. What are you thinkin'?

**Comment by samelhusseini** [comment]
I like the idea of having multiple PR templates. Most people will go through the default one, which can be generic, but we can add links on the wiki to create PR templates for specific plugin types.

For example, for fields, we want to collect things like: 
- Main screenshot of field
- Config options
- Screenshots
- Additional Info

eg: https://github.com/google/blockly-samples/pull/266

**Comment by rachel-fenichel** [comment]
+1 to adding a link on the wiki as a way to get them to the right template

**Comment by BeksOmega** [comment]
I'm going to close this as completed by https://github.com/google/blockly-samples/pull/1916 Obviously creating something fancy wasn't that important to us.
