### ISSUE TITLE
Toolbox search

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#242]
**Category**

Plugin

**Component**

@blockly/plugin-toolbox-search

**Is your feature request related to a problem? Please describe.**

It can be hard to find a block in the toolbox, even when you know which block you want.

**Describe the solution you'd like**

A Search category in the toolbox with a text field.  The user types in the text field and the blocks in the flyout update in response.

**Describe alternatives you've considered**

The text field could be in either the category name or the flyout for the category.

**Additional context**

APIs needed in core Blockly:
- Ability to import a toolbox category and use it with your own toolbox
- (Possibly needed) Ability to add arbitrary UI elements in the toolbox category menu

See also: 
- https://github.com/google/blockly/issues/3851
- https://github.com/google/blockly/issues/766

**Comment by mmvarma-pro** [comment]
Hello guys,
Whats the progress on this feature? It would help me a lot to have this feature. Please reply me as soon as possible. Thank you for being a good community guys. Because of guys like you, repos like these are alive.

**Comment by alschmiedt** [comment]
Hello! Unfortunately, we do not currently have plans to add this plugin. However, we are always open to contributions and have some information on [building plugins](https://developers.google.com/blockly/guides/plugins/overview) if you are interested.

**Comment by mmvarma-pro** [comment]
Please, I am very much interested. Please guide me.

**Comment by LCGF00** [comment]
Imagine having 3K + blocks
a hell to find =P
