### ISSUE TITLE
Add screenshot downloading to dev-tools

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#245]
**Category**

Plugins

**Component**

Part of dev-tools.

**Is your feature request related to a problem? Please describe.**

It's often helpful to download a screenshot of your blocks during development or debugging.

We have some code to do this in core Blockly. It's not ready to be published for users, but is ready to be used by developers.

**Describe the solution you'd like**

- Copy the contents of [screenshot.js](https://github.com/google/blockly/blob/master/tests/playgrounds/screenshot.js) from the core Blockly repository
- Add a way to initialize it onto a workspace to put it in the context menu.

**Desired functionality**
- A context menu option on the workspace to download a screenshot of all blocks on the workspace.
- (optional) A context menu option on blocks to download a screenshot of the selected block (or block stack?)

 **APIs needed in core Blockly**
- Possibly https://github.com/google/blockly/issues/3237

**Additional context**

- https://github.com/google/blockly/issues/2914
- https://github.com/google/blockly/issues/3238
- Adding this to dev-tools doesn't remove the request to have it as a general-purpose plugin

**Needs discussion**
- API
- Tests

**Comment by maribethb** [comment]
I think this is already done, in that it's part of dev-tools and in the context menu in the advanced playground automatically. The separate feature request for a standalone plugin is still open.

Please reopen if I've misunderstood the remaining work.
