### ISSUE TITLE
Add a Scratch jr style sample

### ISSUE THREAD

**Issue by Davidzhu001** [RaspberryPiFoundation/blockly-samples#26]
how can i add blockly jr to this project?

**Comment by RoboErikG** [comment]
Blockly Jr style blocks aren't currently supported by Blockly, though they are supported by [Scratch's fork](https://github.com/llk/scratch-blocks). If you wanted to build a sample showing how to add them start by taking a look at the [hackathon instructions](https://sites.google.com/view/blockly-user-summit-2019/hackathon/rendering-quick-start) for the new rendering APIs.
