### ISSUE TITLE
gui controls should find all registered renderers and themes

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#263]
**Category**
Plugins

**Component**

`@blockly/dev-tools`

**Is your feature request related to a problem? Please describe.**

I want to be able to add and test a new theme or renderer in a playground that uses `addGUIControls`.

**Describe the solution you'd like**

Find all registered themes and renderers and add them to the corresponding dropdowns on GUI controls automatically.

**Describe alternatives you've considered**

Expose an API for setting what the dropdown values could be.

**Comment by samelhusseini** [comment]
Renderers totally makes sense, and that is doable. 
Themes might be harder as we don't register themes. However, instead of https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/addGUIControls.js#L113, we could iterate on the Blockly.Themes object.

**Comment by rachel-fenichel** [comment]
For renderers: sounds good.

For themes: should we be registering themes explicitly instead of (or in addition to) adding them to the Blockly.Themes object?

**Comment by samelhusseini** [comment]
Yeah I see no reason that they should be different, that would allow us to use a theme name in options, eg:
```
Blockly.inject('blocklyDiv', {
   theme: 'modern',
});
```

**Comment by rachel-fenichel** [comment]
I filed an issue on the main repo for theme registry.

- [x] Renderers
- [ ] Themes
  - Depends on https://github.com/google/blockly/issues/3887
