### ISSUE TITLE
Custom generator codelab

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#273]
**Category**

Codelab

**Component**

Building a Custom Generator

**Is your feature request related to a problem? Please describe.**

We have no instructions on how to do this.

**Describe the solution you'd like**

Title: Building a custom generator

What you'll learn: 
- How to define a custom generator
- How to use your custom generator in a playground

**Describe alternatives you've considered**

More documentation on devsite.

**Additional context**

See [Writing a Codelab](https://github.com/google/blockly-samples/wiki/Writing-a-Codelab)

Next steps: 
- Flesh out the outline
- Decide what the custom generator will do and what language it will generate?

**Comment by rachel-fenichel** [comment]
See also: https://github.com/google/blockly/issues/774

**Comment by rachel-fenichel** [comment]
Proposed outline, with stand-in comments in various places:

## Codelab overview
### What you'll learn
- How to create a custom language generator.
- How to create block generator definitions for existing blocks.
- How to create block generator definitions for new block.
- How to use a custom generator in the playground.

### What you'll build

You will build a JSON generator that implements the JSON language spec.

### What you'll need

- Familiarity with JSON and the JSON specification.
- Comfort with defining blocks and toolboxes.

This codelab assumes that you are already comfortable with using the Blockly playground locally.  You can find it in `tests/playground.html`.

## Setup

In this codelab you will add code to the Blockly playground to create and use a new renderer. The playground contains all of Blockly's base blocks, as well as some that exist only to test rendering code. You can find the playground at `tests/playground.html`.

To start, create a file named `custom_renderer.js` in the same folder as the playground.  Include it with a script tag.

```
<script src="custom_renderer.js"></script>
```

Note: you must include your custom code *after* including the Blockly library.

### Block definitions

(I will provide block definitions for the two custom blocks I need).

### Toolbox definition

(I will provide a toolbox definition, in XML or JSON, and explain how to add and use it.

## The basics

The first step is to define and call your generator.

### Create your generator

A custom generator is simply an instance of `Blockly.Generator`. Call the constructor, passing in your generator's name, and store the result.

```js
let myGenerator = new Blockly.Generator('codelab');
```

### Call your generator

Put some blocks on the workspace and call your generator to see what it does.

The only entry point you should use is `workspaceToCode`. This function calls `init` and `finish` to do any additional setup and teardown that your generator needs.

:star: But why are the other functions public?
- Because you still need to be able to access them from your individual block generators, which means that they cannot be private or protected.

```js
myGenerator.workspaceToCode(Blockly.getMainWorkspace());
```

### Expected results

Nothing good should come of this, because you haven't defined generators for the blocks that you had on the workspace.

## Block generator overview
This section and its subheadings will mostly be copied from https://developers.google.com/blockly/guides/create-custom-blocks/generating-code

### Value to code

### Statement to code

### Block to code

### Operator precedence

## Value block generators

- string
- number
- null
- boolean

These use value to code and operator precedence.

## Array block generator
```
[ a, b ]
```
This adds in a variable number of inputs.

## Member block generator
```
"a" : b,
```
In this section, explain blockToCode and scrub.

## Object block generator

```
{
  "a": b,
}
```
This uses a statement input.

## Putting it all together
Call the new generator to generate your code, and check the results.

## Other topics
A quick overview of other generator topics not covered in this codelab.

### Reserved words
e.g. for, while, break. Different per language.

### Indentation
Set how indentation works (tabs vs spaces, etc).

### Variables
Describe how generators handle variables, the variable DB, and why init and finish are important.

## Summary
In this section, recap the work the developer has done and suggest ways to use it.

### Resources
- https://developers.google.com/blockly/guides/create-custom-blocks/generating-code
- Link to published codelab code, including blocks, toolbox, and generator

**Comment by rachel-fenichel** [comment]
Published: https://blocklycodelabs.dev/codelabs/custom-generator/index.html#0

**Comment by wulph111** [comment]
The code lab generates invalid json, trailing commas are not allowed. What is the best way to fix this issue? 

![image](https://user-images.githubusercontent.com/22044501/110233377-952e7500-7ef1-11eb-80b0-12f9f0b8d9e2.png)

**Comment by rachel-fenichel** [comment]
@wulph111 good catch. I just filed an issue for it, and included notes on how to fix it. Do you want to take it?

The codelabs are written as markdown in this repository, so editing them is fairly straightfoward.

**Comment by wulph111** [comment]
Thanks for the kind invitation, @rachel-fenichel. I'm not sure how to contribute changes; would this be a fork and pull-request situation?

 I'll follow up in the new issue you filed.
