### ISSUE TITLE
Copy Blockly getting started codelab to this repo

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#278]
**Category**
Codelabs

**Component**

Learning to use Blockly on the web.

**Is your feature request related to a problem? Please describe.**

There's a good codelab for getting started, but it's hosted on codelabs.developers.google.com instead of blocklycodelabs.dev

**Describe the solution you'd like**

Copy contents of https://codelabs.developers.google.com/codelabs/blockly-web/index.html#0 to this repository and publish.

**Describe alternatives you've considered**

Just link to it from blocklycodelabs.dev

**Additional context**
https://groups.google.com/forum/#!msg/blockly/wkhm4ILSnAc/luClCmC8AwAJ

**Comment by rachel-fenichel** [comment]
Step 1: figure out where this codelab is actually stored. I can't find a repository for it [here](https://github.com/googlecodelabs).

**Comment by rachel-fenichel** [comment]
I've found the codelab contents and am copying it over. Some immediate questions:
- Should we move the starter code + completed code over to this repository?  
  - Currently it lives [here](https://github.com/google/blockly/tree/master/demos/codelab).
- Do we really need the chrome web server for this?
- How should we tell people to include Blockly? 
  - I'm thinking unpkg, so that it's a simple script tag, but with pointers to the rest of the samples for various ways to include it.
- Should we remove this from the main google codelabs site once we publish it outselves?
  - I think yes.

**Comment by samelhusseini** [comment]
> Should we move the starter code + completed code over to this repository?

Yes, let's move to examples.

> Do we really need the chrome web server for this?

No, if there's a need for a webserver, just use the ``http-server`` node module

> How should we tell people to include Blockly?

Agreed, it's the easiest way to include Blockly.

> Should we remove this from the main google codelabs site once we publish it outselves?

Yes as well.

**Comment by rachel-fenichel** [comment]
I actually think it doesn't even need to be served--can just open index.html in a browser.

**Comment by rachel-fenichel** [comment]
Done: https://blocklycodelabs.dev/codelabs/getting-started/index.html?#0
