### ISSUE TITLE
No workspace specified in workspaceToCode call

### ISSUE THREAD

**Issue by lohmanndouglas** [RaspberryPiFoundation/blockly-samples#306]
**Category**
 - Examples

**Component**

 - blockly-react

**Describe the bug**

blockly.js:861 No workspace specified in workspaceToCode call.  Guessing.
Blockly.Generator.workspaceToCode @ blockly.js:861

**To Reproduce**

1. Run react example
2. Generate code
3. Will see the warning in the console

**Expected behavior**
The workspace is not identified, in a scenario with multiples workspaces it could be a problem. 

**Screenshots**

![Console](https://user-images.githubusercontent.com/9731599/84502402-a7df8a80-ac8e-11ea-8ac8-8203d7f577e9.png)

**Additional context**

Solution for this problem is:

```sh
  generateCode = () => {
    var code = BlocklyJS.workspaceToCode(this.simpleWorkspace.current.workspace);
    console.log(code);
  }
```
May I open a pull request with this solution?

**Comment by samelhusseini** [comment]
A PR would be very much appreciated!
