### ISSUE TITLE
Add tooltips/help text on items in gui controls

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#320]
**Category**

Plugins

**Component**

@blockly/dev-tools

**Is your feature request related to a problem? Please describe.**

It's hard to know what all of the actions in the gui controls do, and there isn't room for more descriptive names. The menu is already pretty packed.

**Describe the solution you'd like**

Help text, probably as tooltips, explaining what each action/toggle/etc will do.

**Describe alternatives you've considered**

A single help page somewhere explaining them.

**Additional context**

![image](https://user-images.githubusercontent.com/13686399/86984288-0b9c8c80-c143-11ea-8679-3d5186e9e2ce.png)

**Comment by pakya-1909** [comment]
Hii, @rachel-fenichel i want to work on this issue , if anyone is not working in this issue please assign it to me .

**Comment by rachel-fenichel** [comment]
@pakya-1909 go for it!

**Comment by pakya-1909** [comment]
i just wanted to confirm that the left most navigation bar should have a tooltips when we hover on the items in the link given below.

 [https://docs.google.com/document/d/19JOlKJj5ySXmG1G0hc_r06fYa81uxAaap_-q5hWl5DU/edit?usp=sharing](url)

if not then can you please give me the link of the page.

**Comment by pakya-1909** [comment]
i just wanted to confirm that the left most navigation should have a tooltips when we hover at the items.
![Screenshot (1)](https://user-images.githubusercontent.com/60099099/91839413-a5c51080-ec6c-11ea-9007-c51a11ea805b.png)

if not could you please provide me the link of that page.

**Comment by pakya-1909** [comment]
i just wanted to be sure that the pic below should show tooltips when it is hover at the categories like input, color, loop etc.
if i am wrong please help me :)


![Screenshot (3)](https://user-images.githubusercontent.com/60099099/91864115-7e327000-ec8d-11ea-8f30-a888170ebfbb.png)

**Comment by BeksOmega** [comment]
Hi @pakya-1909 I'm not sure, but I think the target of this issue was actually the advanced playground:
![AdvancedPlayground](https://user-images.githubusercontent.com/25440652/91865481-4ba15c80-ec26-11ea-9be1-fc349277c24a.png)

The source of which can  (I believe) be found [here](https://github.com/google/blockly-samples/tree/master/plugins/dev-tools).

I think the idea was to create some way to attach tooltips to all of the options in the right menu bar, so that developers could know what each control controlled.

**Comment by pakya-1909** [comment]
thanks @BeksOmega :)

**Comment by rachel-fenichel** [comment]
Yes, @BeksOmega is correct about which tooltips I was talking about.

**Comment by pakya-1909** [comment]
i am facing this error and don't know how to solve it......

![Screenshot (4)](https://user-images.githubusercontent.com/60099099/92305131-dc1eca80-efa1-11ea-93f5-0a514e2f1f52.png)

**Comment by pakya-1909** [comment]
what i am thinking to do is to add a tooltips.js file in the html file of the Advance Blockly Playground and then use "Tippyjs npm module" to add tooltips  but i am not able to find the html file or the content files from where it is taken. 

i am facing all these problem because it is my first time to contribute in an open source . 
Please help me .

![Screenshot (5)](https://user-images.githubusercontent.com/60099099/92305519-c27f8200-efa5-11ea-9d67-583709c5c1f7.png)

**Comment by BeksOmega** [comment]
> I am facing this error and don't know how to solve it......

Hmm, it seems like this might be a problem with your IDE? It seems like it's registering certain things as errors, when in my environment they're only warnings:
![Warning](https://user-images.githubusercontent.com/25440652/92315079-d15e3880-ef95-11ea-9ef5-482761330e40.png)

Can you run `npm run start` from the dev-tools directory anyway? It seems like it might from your second picture. If so you should just be able to ignore those "problems" as it calls them :P

If not I'd make sure your IDE knows you're writing in JavaScript (not TypeScript or something). And then I'd look through the settings and try to disable those errors.

> what i am thinking to do is to add a tooltips.js file in the html file of the Advance Blockly Playground and then use "Tippyjs npm module" to add tooltips but i am not able to find the html file or the content files from where it is taken.

That sounds like it should probably work. But I've never really worked with Tippyjs or dat.gui (which defines the menu) so I'm not sure. One thing that might be helpful is the [dat.gui api page](https://github.com/dataarts/dat.gui/blob/master/API.md).

It seems like what you might want to do is whenever a [Controller](https://github.com/dataarts/dat.gui/blob/master/API.md#Controller) is [.add()](https://github.com/dataarts/dat.gui/blob/master/API.md#GUI+add)-ed, get the [domElement](https://github.com/dataarts/dat.gui/blob/master/API.md#Controller+domElement) of it, and apply a Tippyjs tip to it. That's my first instinct anyway =)

@samelhusseini  may also have advice.

> I am facing all these problem because it is my first time to contribute in an open source.

It's so awesome that it's your first time contributing! Thank you for deciding to do that here hehe. You definitely bit off a big project for your first one though! So if you have any more questions please definitely ask :D I'm confident you can do it!

**Comment by pakya-1909** [comment]
I am using windows that is why i am facing these problems .
so i am switching to ubunto .

i run the command  => **npm run start**  and below are the errors 


![Screenshot (7)](https://user-images.githubusercontent.com/60099099/92324580-b0164e80-f060-11ea-81cd-cbb2ab94a6c1.png)

**Comment by BeksOmega** [comment]
Well that problem you can definitely fix! You should just need to click that CRLF and it will give you an LF option.
![Err](https://user-images.githubusercontent.com/25440652/92327321-a0214f00-f00d-11ea-8a1a-c8b11e3a8b27.png)

**Comment by pakya-1909** [comment]
i added tooltips on the **example.html** which is in the dat.gui which is in the node_modules . ( just for an example )
what i did is added an id element in the span tag and then use tippyjs CDN links to add tooltips.

if it is fine than i will do the same on this issue.

i have attached an image which will clear everything. if i am not able to explain it properly.

and thanks for the **_HELP_** and the **OPPORTUNITY** @BeksOmega @rachel-fenichel 

![Screenshot (8)](https://user-images.githubusercontent.com/60099099/92429326-317bf700-f1af-11ea-972b-e43a808b7fa0.png)

**Comment by BeksOmega** [comment]
That looks really cool @pakya-1909 ! Thank you for working on this :D

**Comment by pakya-1909** [comment]
i have made the changes in the dat.gui.js file basically i add id's attribute to li tags and span tags ( in line 1869 of and 2320 i added  name.id = property and  titleRow.id = params.name  respectively )
then install tippy.js and add the tooltips in the addGUIcontrols.js file .
i have only added tooltips to Option , Debug, Action( basically it is a try and to know that it is working or not) if it is working then i will make the tooltips more informative

**Comment by pakya-1909** [comment]
i am not able to make  pull request
it is saying that --> permission to google/blockly-samples.git denied to pakya-1909
fatal :  Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

what should i do??

**Comment by BeksOmega** [comment]
@pakya-1909 which branches do you currently have selected? Could you send a picture like the following, that shows how you're trying to create the pull request?
![ComparingChanges](https://user-images.githubusercontent.com/25440652/93020532-7b3f5580-f592-11ea-83cb-9945d077b5bb.png)

Or if that's not where the error is occuring, could you send a picture of where it is?

I'm sure we can get this figured out :D --Beka

**Comment by pakya-1909** [comment]
i have selected master branch.

![Screenshot (9)](https://user-images.githubusercontent.com/60099099/93020941-bc208400-f5fd-11ea-91df-d19127dcd692.png)

**Comment by BeksOmega** [comment]
It looks like this might be because your [other pull request](https://github.com/google/blockly-samples/pull/354) is still open.

I assume you've made some changes based on Sam's feedback? If you added those changes to your fork's master branch you can just push those changes to your fork, and it will update the existing PR.

If you added those changes to a different branch (besides master) you will need to push that branch, and then make a new pull request with that branch instead of master.

Does that help?

**Comment by pakya-1909** [comment]
thanks for the help, it really worked :)
i have made a pull request let me know if it is not working ?

**Comment by BeksOmega** [comment]
> thanks for the help, it really worked :)
> i have made a pull request let me know if it is not working ?

LGTM :D (looks good to me)

You'll have to wait for a member of the official dev team to give it a review though hehe. Thanks again for your work!
