### ISSUE TITLE
Add lint --fix option to blockly-scripts

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#332]
**Category**

Plugins

**Component**

`blockly-scripts`

**Is your feature request related to a problem? Please describe.**

I copied in code from blockly that has lots of auto-fixable lint issues, but I'm having trouble getting the `--fix` option through to eslint.

**Describe the solution you'd like**

Pass the option through if provided.

**Additional context**

I also tried just calling `eslint . --fix` from the root of my plugin, but got `cannot find module @blockly/eslint-config`. Running `npm install --save-dev @blockly/eslint-config` did not change the error.

**Comment by samelhusseini** [comment]
Looks like this is done, @rachel-fenichel to confirm.
