### ISSUE TITLE
Switching from one package to another should not persist options

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#336]
**Category**
Plugins

**Component**
dev-tools

**Describe the bug**
While trying to look at the field-date I found that pulling up the test page does not display a toolbox with the field-date in it. I think this has to do with: 
`  createPlayground(document.getElementById('root'), createWorkspace,
      defaultOptions);
`

**To Reproduce**

1. Go to field date
2. run `npm run start`
3. Notice the toolbox is the default toolbox

**Expected behavior**
A toolbox with the field-date.

**Screenshots**

**Additional context**

**Comment by alschmiedt** [comment]
@samelhusseini any context on this?

**Comment by samelhusseini** [comment]
The playground loads the previous setting if one is saved. Try to hit "Reset" to reset options and see if it still repro's.

**Comment by alschmiedt** [comment]
Ah, yup that fixed it. 
Would you have any objections to not saving the toolbox?

**Comment by samelhusseini** [comment]
How is the toolbox different to other options? I'm curious why you wouldn't want that saved.

**Comment by alschmiedt** [comment]
It seems to me that a toolbox is project dependent while most other options are not. When I run a different project I expect whatever toolbox that project is created with to be displayed. Having to hit reset in this case doesn't seem very intuitive.

**Comment by samelhusseini** [comment]
I think that makes a case for having project specific options. ie: some way to tell that you've moved from running the playground from `field-slider` to `field-date`, and I agree those two shouldn't share options. 

As for what options are project dependent, I think it depends on the plugin you're building. eg: if you're building a theme plugin, then the theme is going to be project dependent, and say perhaps you were building something that is RTL specific, then the rtl flag would be.

I think we can pass the current plugin name to the playground through the URL loaded, and have it save options under that domain.
