### ISSUE TITLE
advanced_playground Test URL not loading on Edge browser

### ISSUE THREAD

**Issue by MNSDivya** [RaspberryPiFoundation/blockly-samples#367]
**Describe the bug**

advanced_playground Test URL not loading on Edge browser

**To Reproduce**

1. Go to 'http://google.github.io/blockly/tests/playgrounds/advanced_playground.html'
on edge browser

**Expected behavior**
playground should open. Its opening in chrome browser not in Edge

**Screenshots**
https://screencast.googleplex.com/cast/NDg0MzA3NDM4NTYwODcwNHxjNjBmZmUxMC04OA
![image](https://user-images.githubusercontent.com/56336353/93585768-ed65cf00-f9c4-11ea-82c0-007cdd77af81.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Microsoft edge]
 - Version [ Microsoft Edge 44.18362.449.0]

**Comment by gonfunko** [comment]
This is still broken on pre-Chrome Edge, but works fine on modern Edge. [caniuse.com/usage-table](http://caniuse.com/usage-table) has that (and earlier versions) at .01% usage. Closing as obsolete.
