### ISSUE TITLE
Plugin: Allow only top blocks to be manually disabled

### ISSUE THREAD

**Issue by jollytoad** [RaspberryPiFoundation/blockly-samples#369]
### Problem statement

I like the behaviour of Blockly.Events.disableOrphans, but it only makes sense in conjunction with the workspace disable option - to suppress the 'disable' item from the context menu.

I'd still like the user to be able to disable top blocks though via the menu.

I'm proposing an option to allow the disable menu item to still be available for just these blocks.

Maybe a third value for disable, eg: 'onlyTop'?

Blockly.BlockSvg.prototype.showContextMenu_ would check for this and check whether the block was a 'top' block (in the same way that Blockly.Events.disableOrphans does) to determine whether to add the menu item.

I'd be happy to supply a PR for this if you feel it's something useful enough to add to the core.

**Comment by rachel-fenichel** [comment]
Interesting.  I haven't heard requests for this before.  @NeilFraser do you have an opinion on this one?

I think this is trivial to achieve by setting the workspace `configureContextMenu` function.  Is that what you've done?

**Comment by rachel-fenichel** [comment]
The new contextmenu API makes this trivial: we can build it as a plugin that:
- unregisters the existing disable option
- changes the preconditionFn to check it it's a top block
- registers it again

**Comment by maribethb** [comment]
Even  better,  you  don't have to register and unregister. You  can just  `getItem` and change it directly, which avoids some problems with inserting it back into the correct order.
