### ISSUE TITLE
Plugin for scrolling while dragging a block

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#372]
**Category**

 Plugins

**Details**

Create a plugin that allows the workspace to scroll as a user drags a block to the edges of the workspace.

**Comment by alschmiedt** [comment]
Closing since this is now a [plugin](https://github.com/google/blockly-samples/tree/master/plugins/scroll-options). It can now be found on [npm](https://www.npmjs.com/package/@blockly/plugin-scroll-options).
