### ISSUE TITLE
Grid dropdown field

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#373]
**Category**

 Plugins

**Details**

Create a field that allows a user to select an image/text from a dropdown. The images/text should be in grid format. The current dropdown field supports images, but not in grid format, which is better for small images especially.

**Comment by moniika** [comment]
Initial PR with implementation created (#398). Remaining work:
- [x] Support configuring number of columns in constructor and use in CSS styling
- [x] Test that grid dropdown does not affect styling of regular dropdowns (and add non-grid dropdowns to test playground)
- [x] Write tests
