### ISSUE TITLE
play_sound blocks never found

### ISSUE THREAD

**Issue by learellanom** [RaspberryPiFoundation/blockly-samples#393]
Blockly.defineBlocksWithJsonArray([
  {
    "type": "play_sound",
    "message0": "Play %1",
    "args0": [
      {
        "type": "field_dropdown",
        "name": "VALUE",
        "options": [
          ["C4", "sounds/c4.m4a"],
          ["D4", "sounds/d4.m4a"],
          ["E4", "sounds/e4.m4a"],
          ["F4", "sounds/f4.m4a"],
          ["G4", "sounds/g4.m4a"],
          ["A5", "sounds/a5.m4a"],
          ["B5", "sounds/b5.m4a"],
          ["C5", "sounds/c5.m4a"]
        ]
      }
    ],
    "previousStatement": null,
    "nextStatement": null,
    "colour": 355
  }
  ]);

this piece of code does not work , can find the type of the blocks

**Comment by rachel-fenichel** [comment]
I assume that this is a question about [step 6](https://blocklycodelabs.dev/codelabs/getting-started/index.html?index=..%2F..index#5) of the Getting Started codelab. 

The problem is probably that you did not add the script tag to include your new block definition before you tried to use the block in the toolbox.

I'm closing the issue, but let me know if that doesn't fix it.

**Comment by bnmnetp** [comment]
that does not fix the problem.  The problem is that there are files missing in the sounds/ folder

```
ls sounds
c4.m4a  c5.m4a  d4.m4a  e4.m4a  f4.m4a  g4.m4a
```

**Comment by rachel-fenichel** [comment]
@bnmnetp I updated the block definition in the codelab text and completed code. That update will go out next time we publish the codelabs.

**Comment by bnmnetp** [comment]
Thanks.

I was hoping that you had the sound files laying around somewhere so we could have the full scale.  😄 But perhaps I can find some on my own.

**Comment by rachel-fenichel** [comment]
@NeilFraser do you have the m4a files for the rest of the scale? My fix was a bit lazy.

**Comment by NeilFraser** [comment]
I'm very certain I've never seen those files before.  For one, I'd never use the m4a format, it's less well supported by browsers than mp3.  For another, that piano sounds horrible.

Better sounds may be found here:
https://github.com/google/blockly-games/tree/master/third-party/soundfonts/piano
