### ISSUE TITLE
react example: using deprecated libraries

### ISSUE THREAD

**Issue by LarryKlugerDS** [RaspberryPiFoundation/blockly-samples#4]
Thank you for the react blockly example!
But npm install reports several deprecated libraries are being included:

````
npm WARN deprecated fsevents@2.0.6: Please update: there are crash fixes
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
````

Also a warning that may or may not be important:
````
node-pre-gyp WARN Using request for node-pre-gyp https download 
````

Can these warnings be fixed? Thank you,
Larry

ps. Unfortunately I'm still quite new to ReactJS or I'd try to fix them myself.

**Comment by samelhusseini** [comment]
I've checked in the package-lock.json, and ran an ``npm audit``. Let me know if you're still seeing this with the latest changes.

**Comment by LarryKlugerDS** [comment]
Thank you!!
