### ISSUE TITLE
plus-minus not compatible with minified blockly

### ISSUE THREAD

**Issue by BeksOmega** [RaspberryPiFoundation/blockly-samples#407]
**Category**

 - Plugins

**Component**

plus-minus

**Describe the bug**

It seems that when blockly gets minified [`getVars()`](https://github.com/google/blockly/blob/31ee4ead4ae9d0da00d54ba5aa636d2bad59ec18/blocks/procedures.js#L269) gets changed to `.arguments_`.

This causes a problem with the plus-minus package because in that case `.arguments_` is undefined. Those blocks override [`getVars()`](https://github.com/google/blockly-samples/blob/a01452b478d3632082a813b7f92698eb75583b66/plugins/block-plus-minus/src/procedures.js#L525) to use their own internal data.

So if you are using the plus-minus package with minified blockly, you get errors when you attempt to do code generation.

**Stack trace**

I got this from the [original forum post](https://groups.google.com/g/blockly/c/KQS4cTwj4xo).

```
TypeError: Cannot read property 'length' of undefined.
Blockly.BlockSvg.Blockly.JavaScript.procedures_defreturn
node_modules/blockly/javascript.js:89

89 | blah blah blah for (var k=[],h=0;h<a.arguments_.length;h++) blah blah blah
```

Normally that for loop would look like (see [here](https://github.com/google/blockly/blob/31ee4ead4ae9d0da00d54ba5aa636d2bad59ec18/generators/javascript/procedures.js#L52)):
```
  var variables = block.getVars();
  for (var i = 0; i < variables.length; i++) {
    args[i] = Blockly.JavaScript.variableDB_.getName(variables[i],
        Blockly.VARIABLE_CATEGORY_NAME);
  }
```

**To Reproduce**

The [original forum post](https://groups.google.com/g/blockly/c/KQS4cTwj4xo) says that you an reproduce this by adding the procedure_defnoreturn block to the initialXml in App.js in the blockly-react example.

I was not able to reproduce this, because I couldn't get the react sample to load at all :/

**Expected behavior**

No errors.

**Additional context**

I'm not sure how to resolve this :/

**Comment by rachel-fenichel** [comment]
React sample not loading sounds like a different but also serious issue.

Compressing may be renaming anything that is not explicitly marked public. If so, adding `@public` to that function and then recompressing to test should work.

**Comment by BeksOmega** [comment]
I think this can be closed for now. I got the react sample working (I had a bad node version), and I wasn't able to reproduce this. I tried a dev build and a production build, and they both worked.

The developer who originally reported this issue also said it's fixed, so I'm pretty confident it's good? But if someone else wants to try as well before closing, I wouldn't fault you hehe
