### ISSUE TITLE
ghpages deployment additions

### ISSUE THREAD

**Issue by samelhusseini** [RaspberryPiFoundation/blockly-samples#414]
**Category**

Plugins

**Component**

gh-pages deployment of plugins

**Describe the solution you'd like**

 - [x] Pull in package name and add a link to npm.com/@blockly/package-name

**Additional context**

@rachel-fenichel FYI

**Comment by rachel-fenichel** [comment]
#420 
#419 
#418 

All are gh-pages additions.

My next step is to access each plugin's `package.json` in the `prepareToDeployToGhPages` task, pull out relevant variables, and put those into the frontmatter that I'm adding to each plugin index page. That will give us the plugin name and npm link.
