### ISSUE TITLE
Issue installing strict-connection-checker

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#435]
From the [forum](https://groups.google.com/g/blockly/c/zikZPltFHxw/m/PiAhqxJOAwAJ).
**Category**
 - Plugins

**Component**

`plugin-strict-connection-checker`
**Describe the bug**

From the forum:

> 
>  Thanks for your swift answer Rachel!
> Was not able to add the plugin, see bellow.
> Cheers!
> Oded
> 
> yarn add @blockly/plugin-strict-connection-checker
> 
> yields:
> 
> yarn add v1.22.4
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> ....
> error. ....../node_modules/@blockly/plugin-strict-connection-checker: Command failed.
> Exit code: 127
> Command: blockly-scripts postinstall
> Arguments:
> 
> And indeed trying to import:
> 
> import {pluginInfo as StrictConnectionsPluginInfo} from '@blockly/plugin-strict-connection-checker';
> 
> Results in:
> 
> TypeError: Class extends value undefined is not a constructor or null

**Additional context**

Based on the type error at the end, this may be an issue with the peer version of Blockly, but needs investigation.

**Comment by manish-kumar-01** [comment]
Facing the same. when doing 
`npm install @blockly/plugin-strict-connection-checker --save`

Error: 
```
npm ERR! command failed
npm ERR! command sh -c blockly-scripts postinstall
npm ERR! sh: 1: blockly-scripts: not found
```





Any solution?

**Comment by sethswango** [comment]
I am also having this issue. Details here: https://groups.google.com/g/blockly/c/f3UnnQ6EbDU

**Comment by BeksOmega** [comment]
Could not reproduce. I imagine the dev-dependency on blockly-scripts got fixed at some point.
