### ISSUE TITLE
Error when running local events in reverse.

### ISSUE THREAD

**Issue by navilperez** [RaspberryPiFoundation/blockly-samples#45]
Scenario:

| Client 1  | Client 2 | Server |
| ------------- | ------------- | ------------- |
| Move Event A  | Move Event B  |  |
|   |   |  Move Event A <br> Move Event B|
| Move Event B | Undo Move Event B <br> Move Event A <br> Move Event B |

_NOTE: all events are move events for a top level block with no connections_.

Based on the current logic, Client 2 will need to undo Event B in order to get to a common root with the Server before applying the Event A and Event B in the correct order.

When Client 2 attempts to "undo" the event by running it in reverse, there is an error at [Blockly Events, L514](https://github.com/google/blockly/blob/master/core/block_events.js#L514).

> TypeError: Cannot read property 'nextConnection' of null

**Comment by navilperez** [comment]
Things to note:
* Move events run in reverse work by moving a block based on its oldParentId, oldInputName, OldCoordinate.
* When a Blockly Event is serialized, it does not store the oldParentId, oldInputName or OldCoordinate.
* WorkspaceClient currently stores events as JSON.

The reason we are hitting this error is that when we run an event in reverse, we take the event as a JSON from WorkspaceClient and convert it to a new Blockly Event that can be run. However, at this point, the new Blockly Event has lost any information regarding its oldParentId, oldInputName, and oldCoordinate and does not have sufficient information for it to be correctly run in reverse.

To eliminate this error, WorkspaceClient will store local events in their original Blockly Events format so that they retain all information.

**Comment by rachel-fenichel** [comment]
I'm surprised that the JSON event has insufficient information to run it backwards.  Does that mean the event serialization is incomplete?

**Comment by RoboErikG** [comment]
When it was first implemented the undo stack used the event objects directly. Neil suggested skipping the previous state in the serialization to save space on the wire because we didn't think you'd need to undo someone else's changes.

As Navil mentioned, converting the JSON events from the server into Event objects so that you still have the undo info for the local events works around this. I'm unsure if it would be worth the extra data to remove the confusion, though.
