### ISSUE TITLE
Block-Test plugin does not support ie11

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#519]
**Category**
plugins

**Component**
block-test

**Describe the bug**
Trying to test the test blocks on ie11 does not work.

**To Reproduce**
1. Go to ie11 
2. Try to include block-test package using unpkg
**Notice there is an error in concolse**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maribethb** [comment]
Closing: 1. we fixed the problem with publishing uncompiled plugins and 2. Dropping IE support.
