### ISSUE TITLE
Test blocks don't work in hosted playgrounds

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#521]
http://google.github.io/blockly/tests/playground.html?dir=ltr&toolbox=test-blocks On the simple playground on gh-pages, you get an error saying you must run npm install first

https://google.github.io/blockly-samples/plugins/theme-modern/test/# On the hosted demos for blockly-samples, trying to use the test blocks toolbox results in no toolbox loading (and no error messages)

**Comment by moniika** [comment]
Related to https://github.com/google/blockly/issues/4567

**Comment by samelhusseini** [comment]
Closing as the root issue has been resolved upstream.
