### ISSUE TITLE
Circular dependency in block-test and dev-tools

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#523]
**Category**
Plugins

**Component**
@blockly/dev-tools
@blockly/block-test

**Describe the bug**

There is a circular dependency between block-test and dev-tools, causing a warning during install.
This also causes issues with running the block-test plugin directly. Lerna bootstrap must be run before starting the plugin in order to handle this dependency (otherwise there are console warnings and errors while running the plugin).

**To Reproduce**

Run `npm install` in samples directory and see warning about dependency
OR
Run `npm install` on block-test and then `npm run start` and see that the plugin will not load.

**Expected behavior**

There should not be a circular dependency.

**Additional information**

The current workaround for block-test is to run `npm run boot` one directory up before running `npm run start`.

**Comment by suiato** [comment]
Running npm run boot, I get 
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @blockly/block-test -> @blockly/dev-tools -> @blockly/block-test

How to fix this?

**Comment by moniika** [comment]
> Running npm run boot, I get
> lerna WARN ECYCLE Dependency cycles detected, you should fix these!
> lerna WARN ECYCLE @blockly/block-test -> @blockly/dev-tools -> @blockly/block-test
> 
> How to fix this?

You can ignore the warnings and it will not interfere with running other plugins.
As for how to fix these warnings, there isn't a clear answer. Part of fixing this bug is investigating and coming up with a solution.
