### ISSUE TITLE
Disable top blocks plugin should not allow for blocks with disabled (previous) parent to be enabled

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#524]
**Category**
Plugins

**Component**

**Describe the bug**

**To Reproduce**
![e336d043-656c-4bbe-a1e0-6f9ec903ff12 (1)](https://user-images.githubusercontent.com/6621618/102417823-5b646700-3fb1-11eb-8474-7821070885d0.gif)

**Expected behavior**

Enable option should not be available in this case.

**Comment by maribethb** [comment]
Fixed by #536
