### ISSUE TITLE
Error on block test startup

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#535]
**Category**
plugins

**Component**
block-test

**Describe the bug**
When running 'npm run start' in the block test directory we get the following error & the page does not load: 
```
Uncaught Error: Error: Extension "test_dropdown_mutator" is already registered.
```

**To Reproduce**
1. Go to the block-test directory
2. Run `npm run start`
3. Notice the error in the console and the page does not load.

**Expected behavior**
No error in the console and the playground loads.

**Screenshots**

**Additional context**

**Comment by samelhusseini** [comment]
Is this still an issue, I can't repro.

**Comment by alschmiedt** [comment]
Yeah I am still having the problem. If you are not, then could be something I am doing wrong. I checked to make sure I was on master, did a fresh install, and cleared my cache, but the page still won't load.

**Comment by moniika** [comment]
I can repro with the steps:
```
npm install
npm run start
```
and hard refresh of page

I believe this is caused by the circular dependency between @blockly/block-test and @blockly/dev-tools.

I used to be able to resolve it by running `npm run boot` one directory up and then running `npm run start`.
However, now I get an error from the `@blockly/theme-dark` plugin that prevents lerna bootstrap from finishing execution.
```
[kozbial@kozbial plugins](master)$ npm run boot

> blockly-samples@0.0.0 boot /usr/local/google/home/kozbial/github/blockly/samples-moniika
> lerna bootstrap

lerna notice cli v3.20.2
lerna info versioning independent
lerna info Bootstrapping 22 packages
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @blockly/block-test -> @blockly/dev-tools -> @blockly/block-test
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@blockly/theme-dark'
lerna ERR! npm install stderr:
npm ERR! Cannot read property 'match' of undefined
```

**Comment by moniika** [comment]
I've made a PR that updates the package-lock of `@blockly/theme-dark` (#598) which I think should resolve the lerna bootstrap issue.
However, I think we should address underlying cause, which is the circular dependency (#523).

**Comment by moniika** [comment]
Circular dependency tracked in #523.
