### ISSUE TITLE
Move captureWarnings to dev-tools plugin

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#567]
**Category**
plugins

**Component**
dev-tools

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Move `captureWarnings` helper from navigation_modify_test.mocha.js to  dev-tools

**Describe alternatives you've considered**

**Additional context**

**Comment by ricknjacky** [comment]
I'd like to work on this issue. 
Just wanted to ask, all there is to do is move this `captureWarnings` function to `plugins/dev-tools/test/index.js` right?

![image](https://user-images.githubusercontent.com/50985033/111022482-004be000-83f9-11eb-93c5-3c9b286b0be1.png)

**Comment by moniika** [comment]
Not exactly, it should be moved under `plugins/dev-tools/src/`. The dev-tools plugin provides `testHelpers` that are used in other plugins and in core. I'd probably add it to either the [common_test_helpers.mocha.js](https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/common_test_helpers.mocha.js) file or create a new file like utility_test_helpers.mocha.js and also add it as an export in [test_helpers.mocha.js](https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/test_helpers.mocha.js)

**Comment by ricknjacky** [comment]
> Not exactly, it should be moved under `plugins/dev-tools/src/`. The dev-tools plugin provides `testHelpers` that are used in other plugins and in core. I'd probably add it to either the [common_test_helpers.mocha.js](https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/common_test_helpers.mocha.js) file or create a new file like utility_test_helpers.mocha.js and also add it as an export in [test_helpers.mocha.js](https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/test_helpers.mocha.js)

Thanks for the insight, I have opened a PR and did as you've told. 
Please share your suggestions, feedback for the same. Thanks :)

**Comment by ricknjacky** [comment]
>After PR 1 is merged, then we need to wait for publish on npm with the changes from PR 1, and then you can test and merge PR 2

@moniika 
Could you please update me when the changes from my PR linked above are published on npm so that I can start working on PR2

**Comment by rachel-fenichel** [comment]
Edit: I just saw that the merge was a few hours ago. The next publish will be this Thursday.
