### ISSUE TITLE
Enable trash on react application dont display trash

### ISSUE THREAD

**Issue by sginer** [RaspberryPiFoundation/blockly-samples#574]
**Category**

 - Examples

**Component**

Blockly workspace

**Describe the bug**

In the react sample if I enable trash, the trash is not displayed (it is the same with zoom)

This function work fine in Angular

**To Reproduce**

Download github repo
Go to react example
update BlocklyComponent.jsx file and add trashcan option like bellow

        this.primaryWorkspace = Blockly.inject(
            this.blocklyDiv.current,
            {
                toolbox: this.toolbox.current,
                trashcan : true,
                ...rest
            },
        );

Strart the example and you can show on workspace that tras is not displayed

**Expected behavior**

The trash must be displayed when trash is enabled

**Screenshots**

![image](https://user-images.githubusercontent.com/13216494/109776768-3cb25b80-7c03-11eb-836f-8eb1ea057d9a.png)

**Additional context**

**Comment by alschmiedt** [comment]
I am having trouble reproing this. Are you still seeing this issue?

**Comment by sginer** [comment]
yes I have still the problem ! Have you download the react sample, add  previous lines ? When you do this you have the trash enabled ?

**Comment by gonfunko** [comment]
This appears to work fine at present. If you're still experiencing this with the latest version of the example, please feel free to re-open!
