### ISSUE TITLE
"How to Write a Good Issue" leads to moma

### ISSUE THREAD

**Issue by aadsm** [RaspberryPiFoundation/blockly-samples#580]
https://github.com/google/blockly-samples/wiki/How-to-Write-a-Good-Issue

It requires a google.com account to access.

**Comment by samelhusseini** [comment]
Thanks for pointing that out. Fixed.

**Comment by rachel-fenichel** [comment]
Shoot, that's probably true for all of the redirect links on the wiki, because I put them up at the same time.
