### ISSUE TITLE
Custom generator codelab generates invalid JSON

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#581]
**Category**

 - Codelabs

**Component**

custom-generator

**Describe the bug**

The generated code has a comma at the end of each member statement. There should only be a comma between member lines, not after the last one in an array or object.

Reported here:
https://github.com/google/blockly-samples/issues/273#issuecomment-792235455

**Steps to fix**

Update the generators in the codelab:
- The [array block generator](https://github.com/google/blockly-samples/blob/master/codelabs/custom_generator/custom_generator.md#format) should not add the trailing comma
- The [scrub_](https://github.com/google/blockly-samples/blob/master/codelabs/custom_generator/custom_generator.md#the-scrub_-function) function should add commas and newlines (which are no longer added by the member generator), and should skip the trailing comma
- The [member block generator](https://github.com/google/blockly-samples/blob/master/codelabs/custom_generator/custom_generator.md#build-the-code-string) should not have a comma at the end of the line
  - (I think) The member block generator should also not add a newline (since sometimes the end of the line should actually be a newline and comma, and other times it's just a newline). Newlines should be added by the caller instead.

Explanations of the changes should be added in all three places.

**Comment by wulph111** [comment]
The array block generator functions correctly as written (the descriptive text is incorrect.)

`    const valueString = values.join(',\n');
`
does not inject a trailing comma.


Here are my modified functions, based on your instructions:

```
codelabGenerator['member'] = function(block) {
    const name = block.getFieldValue('MEMBER_NAME');
    const value = codelabGenerator.valueToCode(block, 'MEMBER_VALUE',
        codelabGenerator.PRECEDENCE);
    const code = '"' + name + '" : ' + value + '';
    return code;
};

codelabGenerator['object'] = function(block) {
    const statement_members =
        codelabGenerator.statementToCode(block, 'MEMBERS');
    const code = '{\n' + statement_members + '\n}';
    return [code, codelabGenerator.PRECEDENCE];
};

codelabGenerator.scrub_ = function(block, code, opt_thisOnly) {
    const nextBlock =
        block.nextConnection && block.nextConnection.targetBlock();
    let nextCode = '';
    if (nextBlock) {
        nextCode =
            opt_thisOnly ? '' : ',\n' + codelabGenerator.blockToCode(nextBlock);
    }
    return code +  nextCode;
};
```

**Comment by rachel-fenichel** [comment]
Looks good. Your next steps:
- [Fork this repository](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)
- Make changes in [custom_generator.md](https://github.com/google/blockly-samples/blob/master/codelabs/custom_generator/custom_generator.md)
- [Make a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

We'll handle updating the published site once your change is in.
