### ISSUE TITLE
@blockly/block-extension-tooltip doesn't match naming convention

### ISSUE THREAD

**Issue by samelhusseini** [RaspberryPiFoundation/blockly-samples#594]
Our own block-extension (`@blockly/block-extension-tooltip`) doesn't abide by the naming convention on: 
https://developers.google.com/blockly/guides/plugins/naming

Options are:
- **Change the naming convention** for block (since it's early enough), and before we showcase this at the summit.
 - Other reasons for changing the name convention from `@blockly/extension-*` to `@blockly/block-extension` is to reduce overload of the word extension as it's very synonymous with plugin and it's not obvious what the difference between `@blockly/extension-*` and `@blockly/plugin-*` is.
- **Ignore**, and new plugins can use the current convention.
- **Re-publish the plugin under `@blockly/extension-tooltip`**, deprecating the old one.

**Comment by maribethb** [comment]
Closing since we deprecated this plugin.
