### ISSUE TITLE
Error running nominal-connection-checker

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#604]
**Category**
Plugins

**Component**
nominal-connection-checker

**Describe the bug**

Plugin throws error when run.

```
textModel.ts:50 Uncaught (in promise) TypeError: Cannot read property 'create' of undefined
    at I (textModel.ts:50)
    at o.setValue (textModel.ts:289)
    at loadTab (index.js?0441:158)
    at eval (index.js?0441:226)
```

**To Reproduce**

1. `npm install && npm run start`
2. See error.

**Expected behavior**

No error when running plugin.

**Additional context**

Since this plugin involves local storage, it might be necessary to clear local storage to repro.

**Comment by moniika** [comment]
@BeksOmega

**Comment by BeksOmega** [comment]
Hmm I wasn't able to reproduce. The steps I followed were:
1) Cleared browser cache.
2) Checked out master.
3) `npm install`
4) `npm run start`
5) Observed how the page opened up without errors.
6) Created a type hierarchy and some block definitions.
7) Refreshed page.
8) Observed how the connection checker also worked.

Do you think it could be a platform-specific issue? I'm running currently chrome 89 on ubuntu 18.04

**Comment by moniika** [comment]
Upon investigating, it looks like the 'playgroundState' in my localStorage didn't have 'TypeHierarchy' as key in the object, which was causing the error. I think this was probably caused by running the plugin in an earlier version.
After I clear localStorage, I am able to run the plugin.
However, I do now an alert and error in the console that `textToDom` was unable to parse the xml passed to it.
I'll close this and file a separate bug for it.

**Comment by moniika** [comment]
New issue filed: https://github.com/google/blockly-samples/issues/660
