### ISSUE TITLE
Custom fields in React demo are marked as EDITABLE but not also SERIALIZABLE

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#607]
**Category**

Examples

**Component**

blockly-react

**Describe the bug**

The custom fields in the react demo: `BlocklyReactField` and `ReactDateField` are editable but not serializable, resulting in the warning:
```
blockly_compressed.js:464 Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.
```

**To Reproduce**

Run the react demo and look at console warnings.

**Expected behavior**

These fields should probably be marked as `SERIALIZABLE = true` on the prototype.

**Comment by maribethb** [comment]
This issue would be a good first issue for new contributors. To help you get started, I'll outline the steps you should take to solve this issue. If you have any questions, please ask us!

1. In your clone of blockly-samples, navigate to `examples/blockly-react`
2. Run `npm install` and `npm run start` to start up the demo. This should open a Chrome window with the React demo
3. Open the JavaScript console, and you should see the warning Monica described. `Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.`
4. In your text editor, open the file `examples/blockly-react/src/fields/BlocklyReactField.jsx`. This is one of the fields emitting that warning.
5. Add `SERIALIZABLE = true;` to the class definition.
6. Save, and refresh the Chrome window with the demo running. Check the console, and that warning should disappear. The reason both of them disappear is that the other field, `DateField`, inherits from `BlocklyReactField` so it also inherits this property.
7. Open a PR and address any PR comments. You can run `npm run lint` before doing so to make sure you're following the style guide.

For some more background about fields and the editable/serializable properties, [check out our documentation on this topic](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating#editable_and_serializable_properties).

**Comment by Harshita-Kanal** [comment]
I would like to work on this.
