### ISSUE TITLE
Add publishConfig to package.json templates in dev-create

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#613]
**Category**
Plugins

**Component**
dev-create

**Is your feature request related to a problem? Please describe.**

When we create a new plugin we need publishConfig defined in the package.json and it's often forgotten until it's time to publish and it doesn't work.

**Describe the solution you'd like**

I'd like for publishConfig to be included in the template so it's not forgotten.

**Describe alternatives you've considered**

No change. We manually add publishConfig to scripts in package.json when we create a plugin.

**Additional context**

**Comment by gonfunko** [comment]
This appears to have been resolved: https://github.com/google/blockly-samples/blob/master/plugins/dev-create/bin/plugin.js#L140-L143
