### ISSUE TITLE
`npm run start` should handle the port being in use

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#658]
**Category**

Scripts

**Component**

blockly-scripts start

**Describe the bug**

`npm run start` is configured to use port 3000 to run a plugin test page. If you already have another plugin open, or any other process listening on that port, the script silently fails. The symptom is no meaningful error message but Chrome does not launch as expected.

**To Reproduce**

`npm run start` on a plugin, leave it open
`npm run start` in another tab
Chrome does not open for the second one, no error

**Expected behavior**

Preferred: The script chooses an available port dynamically
Acceptable: An error message saying the port is in use.

**Additional context**

If you think this is happening to you (ie Chrome won't open and you don't know why), you can try
`lsof -i :3000`
If there is any output with a pid, that means there is a process using port 3000 already, and `start` script will fail.
`kill 12345` where 12345 = the pid from the command above. This should kill the process and free up the port.

**Comment by maribethb** [comment]
It looks like if we just didn't specify a port number, webpack-dev-server would find one for us. https://github.com/webpack/webpack-dev-server/pull/685

better example here: https://github.com/webpack/webpack-dev-server/pull/1054

**Comment by samelhusseini** [comment]
Worth considering using https://www.npmjs.com/package/detect-port-alt to detect if the port is in use, and to offer an alternate port.
