### ISSUE TITLE
Publish script starts over at the end, instead of finishing cleanly

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#664]
**Category**

n/a

**Component**
n/a

**Describe the bug**
`npm run publish` command is hanging after publishing plugins.
Additionally, the publish command requested an authentication token twice during the run (hanging after the second time)

**To Reproduce**

1. Run publish script (when there are plugins with changes to publish)
2. Observe script hanging after plugins publish after the logs:
```
> blockly-samples@0.0.0 publish /usr/local/google/home/kozbial/github/blockly/samples-moniika/dist
> gulp publish

[17:38:32] Using gulpfile ~/github/blockly/samples-moniika/dist/gulpfile.js
[17:38:32] Starting 'publish'...
Logging in to npm.
```

**Expected behavior**

Script should finish cleanly and not hang

**Screenshots**
n/a

**Additional context**

Command was run on Linux machine.

**Comment by maribethb** [comment]
This also occurred on macOS.

**Comment by maribethb** [comment]
The reason for this is that our command to publish is called "publish." This is a lifecycle script that lerna calls automatically during the publish process, as described here: 

https://www.npmjs.com/package/@lerna/publish?activeTab=readme#lifecycle-scripts

"To avoid recursive calls, don't use this root lifecycle to run lerna publish"

So we just need to rename our `publish` script to something else and then it won't get called recursively

**Comment by maribethb** [comment]
Fixed in the new process.
