### ISSUE TITLE
Running multiple xml tests causes error in serializeToString

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#665]
**Category**
Plugins

**Component**

**Describe the bug**
The bug occurs when a user runs tests in multiple files that call our `domToText` method. For example, in `block-dynamic-connection` and in `block-plus-minus` we have multiple tests in different files that call `runSerializationTestSuite`.

This has to do with our update to jsdom version 16 in this PR: google/blockly#4573.

**To Reproduce**

1. Go to block-dynamic-connection.
2. Update to version `5.20210325.0` of Blockly.
3. Run `npm run test`.
4. See error `TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.`

**Expected behavior**
The tests should pass. 

**Screenshots**

**Additional context**
- The methods will pass if there is only one file being run.
- The object being passed in to `serializeToString` is the same whether they pass or fail.
- This works with version 15 of jsdom.
- It also worked when we tried running with xmldom.

**Comment by cpcallen** [comment]
Could this be related to multiple loading of Blockly discussed in #902 and #949?

**Comment by alschmiedt** [comment]
Yeah it is very possible. The changes this release seemed to fix this problem since the tests are now passing with the latest version. I don't believe there is any reason to keep this open since we have #949 to track the possible root cause and I do not see a reason to go back and figure out why version 5 was not working. However, feel free to reopen.
