### ISSUE TITLE
Rename variables that start with opt_

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#667]
This is a *good first issue* for people who want to start contributing to this repository.

**Category**

Plugins

**Component**

All plugins

**Describe the bug**

The existing code uses `opt_` as a prefix for optional parameter names. This is based on old recommendations in Google's style guide.

The style guide now [says](https://google.github.io/styleguide/jsguide.html#naming-parameter-names) that parameter names should all be written in `lowerCamelCase`.

You can see all of the places where the wrong naming convention is used by running `npm run lint` from the root of the repository.

**Steps to fix**

1. Run `npm run lint` from the root of the repository.
2. Choose a file with lint errors due to camelcase issues.
3. Replace all names: `opt_someParameterName` should become `optSomeParameterName`.
4. Make a pull request.

**Comment by himanshu007-creator** [comment]
Hi, i  would like to work on this issue. Please guide me further

**Comment by alschmiedt** [comment]
Hello!

Thanks for your interest in the issue! The first step would be to fork the repository, clone it and then follow the steps above. Feel free to respond with any questions.

**Comment by maribethb** [comment]
One slight addition, [this part](https://google.github.io/styleguide/jsguide.html#features-functions-parameter-return-types) of the style guide has additional guidance for optional parameters, including that all optional parameters should have default values in the function declaration, even if the default value is just undefined. Also based on this section I don't think we should include the `opt` prefix at all, even properly camelcased. So I would suggest the steps become
3. Replace all names: `opt_someParameterName` becomes `someParameterName`
4. Add a default parameter value (`function(someParameterName = undefined)`). Adding a better default value based on the function would be fine, but `undefined` should always work as a default.
5. Make a pull request.

@himanshu007-creator Is there anything else you need to know to start working on this? If you're stuck, please let us know which part you need more info about. Thanks!

**Comment by lazy-geek** [comment]
Can this issue be assigned to me?

**Comment by lazy-geek** [comment]
@rachel-fenichel  Should i use specific version of nodejs and npm or will any version do?

Because package.lock.json file changes when i install the dependency , is that expected?

**Comment by rachel-fenichel** [comment]
Any version will do, but just leave the package-lock file out of the resulting pull request.

**Comment by lazy-geek** [comment]
Thanks will do

**Comment by lazy-geek** [comment]
@rachel-fenichel hii again , while renaming these variables i found some function that accept "opt_variablename" named parameter and if i rename it to just "variablename" then there is also a  local variable called "variablename" in the function which conflict with the renamed variable , what should i do about this

### example
![IMG_20210617_223548](https://user-images.githubusercontent.com/38218691/122443803-8ca00d00-cfbd-11eb-8710-95a1eabcd655.jpg)

**Comment by lazy-geek** [comment]
@rachel-fenichel  Also I don't think `npm run lint` is detecting every instance of opt_ variable , should i manually use find and replace?

**Comment by rachel-fenichel** [comment]
If the names are conflicting, pick a new name for either the parameter or the variable name in the function--hopefully most of these are straightforward.

For lint not detecting every instance: Yes, manually using find and replace is fine as well.

Cheers,
Rachel

**Comment by lazy-geek** [comment]
@rachel-fenichel ok
Also just to clarify
By
> **Category**
> Plugins

You mean that these changes only need to be made in Plugins folder right?
