### ISSUE TITLE
Update CONTRIBUTING.md to point at dev site instead of wiki

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#678]
The [CONTRIBUTING](https://github.com/google/blockly-samples/blob/master/.github/CONTRIBUTING.md) file is shown in GitHub to new contributors. This file currently contains links to the blockly-samples wiki. However, this documentation has been moved to the [Blockly Developer Site](https://developers.google.com/blockly/guides/plugins/overview) (most of it under Plugins, but some under Modifying Blockly) and the wiki is not maintained. After this bug is fixed, we should probably clear out the wiki content and point people to the developer site which is more up to date.

This would be a good first issue if you are looking to learn how to contribute to Blockly. You would need to edit the `CONTRIBUTING.md` file linked above and
1. For every link on that page that points to the blockly-samples wiki, replace it with a link to the corresponding article on the Blockly Developer site.
2. If any page in the wiki does not have a corresponding article on the Dev site, open a new GitHub issue asking for the page to be ported (I think they have all been ported already but I could be wrong)

You can always ask us here or on the forum if you would like to help with this issue but need assistance.

**Comment by ShiroRyokoshi** [comment]
I opened a new GitHub issue that asks for the pages to be moved ([issue](https://github.com/google/blockly-samples/issues/679)). When the pages will be moved I will update all links and make a new PR that has all links updated instead of doing one PR now and the second PR later.

**Comment by maribethb** [comment]
Hello, the missing pages have been added to developer site (see #679 for links) so the work for this issue can now proceed. If you are still interested, you can assign the issue to yourself on GitHub so we know you are working on it. Thanks!
