### ISSUE TITLE
Move some GitHub wiki pages to Blockly Developer Site.

### ISSUE THREAD

**Issue by ShiroRyokoshi** [RaspberryPiFoundation/blockly-samples#679]
**Category**

Documentation

**Component**

[CONTRIBUTING](https://github.com/google/blockly-samples/blob/master/.github/CONTRIBUTING.md) and [wiki](https://github.com/google/blockly-samples/wiki)

**Describe the bug**

Some of the links in [CONTRIBUTING](https://github.com/google/blockly-samples/blob/master/.github/CONTRIBUTING.md) link to Github wiki pages instead redirecting the user to the moved pages on [Blockly Developer Site](https://developers.google.com/blockly/guides/overview).

List of links that are affected:

1. [Add a plugin](https://github.com/google/blockly-samples/wiki/Adding-A-Plugin)
2. [Fix bugs](https://github.com/google/blockly-samples/wiki/Finding-a-Good-Issue:-Labels)
3. [wiki](https://github.com/google/blockly-samples/wiki)
4. [overview of the repostiory structure](https://github.com/google/blockly-samples/wiki/Repository-Structure)
5. [publishing process](https://github.com/google/blockly-samples/wiki/Plugin-Publishing)

**To Reproduce**

1. Go to [CONTRIBUTING](https://github.com/google/blockly-samples/blob/master/.github/CONTRIBUTING.md)
2. Click on one of the links that is on the list.
3. See error

**Expected behavior**

After the user clicks the link, he should be redirected to GitHub wiki page that gives the user a link to apropriate [Blockly Developer Site](https://developers.google.com/blockly/guides/overview). 

**Additional context**

Side note. Currently the links redirect to a page on Github wiki that informs the user that he should go to the page on Blockly Developer Site. Not ideal. There is an issue opened about this and I am working on updating it, but I cannot update the links if the pages from the Github wiki are not moved to Blockly Developer Site.

This has been my first ever issue written, I hope I didn't made any mistakes.

**Comment by maribethb** [comment]
Number 1 - Add a plugin should go here: https://developers.google.com/blockly/guides/modify/contribute/add_a_plugin

Number 3 - Link to the [Developer Site](https://developers.google.com/blockly/guides/modify/contributing) instead of the wiki

For 2, 4, and 5 you're right, these are not currently available on the Developer Site. I will work on adding these there and I'll reply with the links when they are live. Thanks for reporting!

**Comment by maribethb** [comment]
The other links are now live on the developer site:
Issue labels (fix bugs): https://developers.google.com/blockly/guides/modify/contribute/issue_labels
Repository structure: https://developers.google.com/blockly/guides/modify/contribute/samples_repository_structure

And publishing was added to the create a plugin page: https://developers.google.com/blockly/guides/modify/contribute/add_a_plugin#publishing

I still need to add a link to these pages on the wiki, but now that they are live on the developer site, you can now work on #678  if you're still interested :)
