### ISSUE TITLE
Cannot use the dependency @blockly/field-grid-dropdown

### ISSUE THREAD

**Issue by YuLei325** [RaspberryPiFoundation/blockly-samples#680]
**Category**
Plugins

**Component**
field-grid-dropdown

**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/34700233/116054922-c71cb600-a6ae-11eb-8601-2c0e1616c0ad.png)
I install the package but I cannot use it. Maybe your package build is wrong.

I install the package but I cannot use it. Maybe your package build is wrong.
**Describe the solution you'd like**
You should publish the package again.

**Describe alternatives you've considered**

**Additional context**

**Comment by alschmiedt** [comment]
Hello! I am having trouble reproducing this issue. How are you importing the package? Have you tried the below steps? 

- npm install @blockly/field-grid-dropdown --save
- Add the following to the file you want to use it in: ```import * as Blockly from 'blockly';
import {FieldGridDropdown} from '@blockly/field-grid-dropdown';```

If you have tried the above steps and it still is not working, what version of the package are you using?

**Comment by YuLei325** [comment]
I’ve tried all the steps which you are mentioned. And I find out that your package doesn’t have types file. So I think maybe the problem is that.



发自我的iPhone


------------------ Original ------------------
From: alschmiedt ***@***.***&gt;
Date: Sat,May 1,2021 3:44 AM
To: google/blockly-samples ***@***.***&gt;
Cc: YuLei325 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [google/blockly-samples] Cannot use the dependency @blockly/field-grid-dropdown (#680)





 
Hello! I am having trouble reproducing this issue. How are you importing the package? Have you tried the below steps?
  
npm install @blockly/field-grid-dropdown --save 

Add the following to the file you want to use it in: import * as Blockly from 'blockly'; import {FieldGridDropdown} from ***@***.***/field-grid-dropdown'; 
 
If you have tried the above steps and it still is not working, what version of the package are you using?

**Comment by gonfunko** [comment]
This plugin has now been converted to TS, so if the issue was related to types files it's presumably been resolved. If you're still encountering issues feel free to reopen though!
