### ISSUE TITLE
In-line text areas for fields on mobile

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#703]
**Category**

Plugins

**Component**

new component

**Is your feature request related to a problem? Please describe.**

“On desktop, fields turn red with the first incorrect character that's entered, but this won't happen for prompts.  Not a big deal for number entry, but bad in my use case with entire lines of code.”

**Describe the solution you'd like**

Custom text field that shows an in-line text area on mobile instead of a popup.

**Describe alternatives you've considered**

**Additional context**

**Comment by BeksOmega** [comment]
This is now possible in core using the `modalInputs` config option.
