### ISSUE TITLE
Use `const` instead of `var` in workspace search

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#719]
**Category**
 - Plugins

**Component**

workspace-search

**Describe the bug**

One of the source files uses `var`. In blockly-samples, this is a lint error as we follow the [Google style guide](https://google.github.io/styleguide/jsguide.html#features-use-const-and-let), which requires that we use `let` or `const` instead of `var`.

**To Reproduce**

Run `npm run lint` in blockly-samples. Two of the lint errors say:  
```
plugins/workspace-search/src/WorkspaceSearch.js#L325
Unexpected var, use let or const instead
```

You can also see this in the lint report of any PR opened in blockly-samples.

**Expected behavior**

This lint error does not exist.

**Additional context**

This would be a good first issue for new contributors. To help you get started, here are the steps you should follow to resolve this issue.

1. In your fork of blockly-samples, open the affected file: https://github.com/google/blockly-samples/blob/master/plugins/workspace-search/src/WorkspaceSearch.js#L325
2. These variables are never reassigned, so they are `const`s. Replace `var` with `const`.
3. Run `npm run lint` to ensure this lint error has been resolved and you have not introduced any others. (There are other lint errors and warnings in blockly-samples, but there shouldn't be any new ones nor any in this particular file).
4. Open a PR and address any comments.

If your PR is accepted and merged, we'll be able to see results right away as there will be one fewer lint error on every PR opened in blockly-samples!

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this issue!

**Comment by alschmiedt** [comment]
Done. Let us know if you have any questions! If you decide to stop working on it let us know and we can remove you from the assignees list.
