### ISSUE TITLE
continuous toolbox docs outdated.

### ISSUE THREAD

**Issue by pelikhan** [RaspberryPiFoundation/blockly-samples#726]
There seems to be a discreptancy between the README displayed at https://google.github.io/blockly-samples/plugins/continuous-toolbox/README

![image](https://user-images.githubusercontent.com/4175913/119074267-92e1a000-b9a3-11eb-977d-851027fca024.png)

and https://github.com/google/blockly-samples/tree/master/plugins/continuous-toolbox

![image](https://user-images.githubusercontent.com/4175913/119074333-ab51ba80-b9a3-11eb-9955-eac73e4405dc.png)

**Comment by alschmiedt** [comment]
Thanks for reporting!

The [fix](https://github.com/google/blockly-samples/pull/718/files) for this was just released so the README should be up to date on [npm](https://www.npmjs.com/package/@blockly/continuous-toolbox) now.

**Comment by pelikhan** [comment]
https://google.github.io/blockly-samples/plugins/continuous-toolbox/README still outdated though
