### ISSUE TITLE
continuous toolbox throws "Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by pelikhan** [RaspberryPiFoundation/blockly-samples#731]
When I try to use the continuous toolbox following the README instructions, I get the following error. I am using the react-blocly NPM package if that matters.

```
TypeError: Class extends value undefined is not a constructor or null
    at Module../node_modules/@blockly/continuous-toolbox/src/ContinuousMetrics.js:14:40
    ...
```

I noticed the demo app also imports ContinuousCategory.js at https://github.com/google/blockly-samples/blob/master/plugins/continuous-toolbox/test/index.js#L13, but that's not in the README.

The PR of my chanages are at https://github.com/microsoft/jacdac-docs/pull/16/files#diff-af35e01693082ac34f1429f799a5c2c414976733487764540a13c2d7b10f5a3bR97

**Comment by alschmiedt** [comment]
What version of Blockly are you using? The `ContinuousToolbox` was updated recently to rely on the newest release of Blockly (5.20210325.1). If you are using an older version of Blockly `Blockly.MetricsManager` would not exist, which might explain the error message you are getting.

**Comment by pelikhan** [comment]
You're right. react-blockly was locked to 3.x. I'll try again with react-blockly 7.0 which now uses blockly 5.x
