### ISSUE TITLE
getBorderColour not in types

### ISSUE THREAD

**Issue by pelikhan** [RaspberryPiFoundation/blockly-samples#735]
Try to recompiled the blockly react field editor to typescript leads to a type error (https://github.com/google/blockly-samples/blob/master/examples/blockly-react/src/fields/BlocklyReactField.jsx) because getBorderColour is missing from the definitions.

![image](https://user-images.githubusercontent.com/4175913/119697000-9f7f5180-be04-11eb-9780-ca885706e961.png)

Is there a best practice to fill up the gaps on the generated type definitions?

**Comment by BeksOmega** [comment]
I think the [typescript defs tracking issue](https://github.com/google/blockly/issues/2937) shows an example of how to add your own defs. But you may want to call [getColourTertiary](https://developers.google.com/blockly/reference/js/Blockly.BlockSvg?hl=en#getColourTertiary) instead (see [deprecation warning](https://github.com/google/blockly/blob/3fe56b083c62549cb2bdb17270846bf17ced5d7a/core/block_svg.js#L282) for getColourBorder).

**Comment by pelikhan** [comment]
Cool thanks. 

This sample needs to be updated to use getColourTeriary --> https://github.com/google/blockly-samples/blob/master/examples/blockly-react/src/fields/BlocklyReactField.jsx#L45

**Comment by maribethb** [comment]
We have https://github.com/google/blockly-samples/issues/608 for that issue, it's good low-hanging fruit for a first-time contributor so it might stick around for a bit (at most, until we decide to remove that function altogether) so in the meantime hopefully one of Beka's suggestions works!
