### ISSUE TITLE
RemoveGenerator function for playground

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#739]
**Category**

 - Plugins

**Component**

dev-tools, specifically the playground.

**Is your feature request related to a problem? Please describe.**

The playground exports a function to [add a generator](https://github.com/google/blockly-samples/blob/master/plugins/dev-tools/src/playground/index.js#L401), but no matching function to remove an existing generator. This can make the page crowded.

**Describe the solution you'd like**

`removeGenerator(name)` function on the playground.

**Describe alternatives you've considered**

**Additional context**

This issue came up through a [forum post](https://groups.google.com/g/blockly/c/BjN1pBP3Dls).

**Comment by BeksOmega** [comment]
Closed by #765
