### ISSUE TITLE
Advanced playground occasionally crashes with too much scrolling

### ISSUE THREAD

**Issue by maribethb** [RaspberryPiFoundation/blockly-samples#750]
**Category**

Plugins

**Component**

dev-tools

**Describe the bug**

Chrome occasionally crashes if you scroll too much/fast in the advanced playground.

**To Reproduce**

1. Open an advanced playground
2. Enable the "mousewheel move" option so that using the mousewheel will move the workspace
3. Drag some blocks onto the workspace, or do an airstrike (I reproduced with only 20 blocks)
4. Scroll rapidly using the mousewheel
5. Chrome will eventually crash, probably. If you have the console open, and you're lucky, Chrome will put a breakpoint just before the out-of-memory error.

**Additional context**

I reproduced this in several different plugins, so I don't believe the issue is with any particular plugin, other than the dev-tools advanced playground itself. I was able to get Chrome to stop once before crashing, and the call stack was somewhere in the [`generate` method](https://github.com/google/blockly-samples/blob/7097e15069d960bcf7eba0752370b145cfe7e95f/plugins/dev-tools/src/playground/index.js#L156). I think this is being called any time the viewport changes. You can see the text in the generator section flashing as you scroll. But I haven't looked any deeper than this yet.

**Comment by BeksOmega** [comment]
It sounds like the new events might need to be filtered out before generating, if so it might be a good idea to update the [realtime generation docs](https://developers.google.com/blockly/guides/configure/web/code-generators?hl=en#realtime_generation) too.

**Comment by maribethb** [comment]
I think this might be related specifically to the monaco editor (the crash happens deeper in the stack than the function linked above, that wasn't clear, sorry) but I'm not sure at this point.
