### ISSUE TITLE
block-test triggers warning about extra unregister

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#770]
**Category**

**Component**
block-test

**Describe the bug**
Warning about extra unregister call is triggered when this plugin is loaded.
```
No extension mapping for name "test_many_blocks_mutator" found to unregister
```

**To Reproduce**

1. Start the block-test plugin by running `npm run start` from the plugins/block-test directory.
2. Observe warning

**Expected behavior**

No warning.

**Comment by BeksOmega** [comment]
Fixing this issue has a few steps:

1) Reproduce the issue using the steps outlined in the "Steps to Reproduce" section. Once you can reproduce the bad behavior, you can test if your changes fixed it.
2) Modify the code in [plugins/block-test/src/mutators.js](https://github.com/google/blockly-samples/blob/master/plugins/block-test/src/mutators.js) to call `Blockly.Extensions.isRegistered` before calling `unregister`.
3) Run the reproduction steps again, and verify that the text is selected when you click on it.
4) Open your PR and resolve any PR comments.

After your PR is accepted, a Blockly team member will have to publish the GitHub Pages site, and then you'll be able to see your change live! Or in this case, you will no longer be able to see the warning in the console on any of our demo sites :D

**Comment by melanie-t** [comment]
I'd like to pick this one up!
