### ISSUE TITLE
Scaffolding for Third Party Plugins

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#777]
**Category**

**Component**
gh-pages

**Is your feature request related to a problem? Please describe.**
We need a place to showcase third party plugins. We currently use [gh-pages](https://google.github.io/blockly-samples/) to display our plugins and examples. We would like to use this same site to display third party plugins. 

**Describe the solution you'd like**
For a third party plugin just display the [README](https://google.github.io/blockly-samples/plugins/block-dynamic-connection/README) page and add links to the github repository and npm page under "View code" and "View on npm". We should also display a banner or something on this page saying that it is a third party plugin.

**Describe alternatives you've considered**
- Add an "Explore plugins" page on the developer guides. 
- Add an example that uses each plugin. This would be nice, but requires more maintenance on our part. 

**Additional context**

**Comment by rachel-fenichel** [comment]
Additional information:
- We use [Jekyll](https://jekyllrb.com/docs/) to make our githb pages content look good
- Jekyll [layouts](https://jekyllrb.com/docs/layouts/) determine what a page looks like
- ['layout' sections](https://github.com/google/blockly-samples/blob/master/gh-pages/_config.yml#L16) in `_config.yml` set which layout is used for each page
- We currently use a layout named [`default`](https://github.com/google/blockly-samples/blob/master/gh-pages/_layouts/default.html) for examples and plugins
- Layouts grab information from a `page` object and can use the information in the page ([for example](https://github.com/google/blockly-samples/blob/master/gh-pages/_layouts/default.html#L28), to add an npm link to the correct package)
- This object is called ["front matter"](https://jekyllrb.com/docs/front-matter/) in Jekyll documentation
- For our examples and plugins we [generate](https://github.com/google/blockly-samples/blob/master/gulpfile.js#L152) front matter during `predeploy`, in addition to running builds and copying files to the correct directories
  - Those end up in the examples and plugins folders that you can see if you switch to the [gh-pages branch](https://github.com/google/blockly-samples/tree/gh-pages)
  - For instance, here's the [index page](https://github.com/google/blockly-samples/blob/gh-pages/plugins/block-test/test/index.html) for the block-test plugin before processing by Jekyll


With all this, I think the steps are:
- Put another folder in the [gh-pages](https://github.com/google/blockly-samples/tree/master/gh-pages) directory, named something like `third-party-plugins`
- Add one page per third-party plugin that we want to showcase
  - Either manually added per third-party plugin, or generated from some data file. Manually added would be sufficient until we get enough that it's cumbersome.
- Add a layout that has links and the readme, but not the playground
- Add a mapping in `_config.yml` to set the layout correctly
- Add links from `gh-pages/index.md`

**Comment by rachel-fenichel** [comment]
Note that this is for making it a nice page per third party plugin. A stopgap is to put a link directly in `gh-pages/index.md` to the correct npm page, and that's a one-liner.
