### ISSUE TITLE
Update visibility of `isBlockMatch_` in `WorkspaceSearch`

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#778]
**Category**
Plugins

**Component**
workspace-search

**Is your feature request related to a problem? Please describe.**
Making it easier to customize workspace search.

**Describe the solution you'd like**
Update visibility of `isBlockMatch_` from `@private` to `@protected`.

**Describe alternatives you've considered**
Leaving as is and developers would instead extend `getMatchingBlocks_`.

**Additional context**

https://github.com/google/blockly-samples/pull/756

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue.

**Comment by alschmiedt** [comment]
Great!

I will assign you to the issue and feel free to comment if you have any questions.
