### ISSUE TITLE
Non text-editable field-date implies unsupported behavior

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#783]
**Category**
Plugins

**Component**
field-date

**Describe the bug**
The text cursor on field-date implies that the text can be selected, but it cannot.

**To Reproduce**

1. Hover over text field on field-date with text edit disabled. (run sample and hover over "simple" field-date)
2. Observe that the cursor is styled as a "text" cursor and that the text is not selectable

**Expected behavior**
Either the text on field-date should be selectable or the cursor should not be a text cursor.

**Comment by gonfunko** [comment]
The new date field plugin has resolved this.
