### ISSUE TITLE
block-extension-tooltip doesn't include dist directory

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#793]
**Category**
Plugins

**Component**
block-extension-tooltip

**Describe the bug**
Looking at the version of block-extension-tooltip, the dist directory was not 
https://unpkg.com/browse/@blockly/block-extension-tooltip@1.0.10/

**To Reproduce**

1. Check https://unpkg.com/browse/@blockly/block-extension-tooltip@1.0.10/
OR
1. Install the plugin using `npm install @blockly-block-extension-tooltip`
2. Expand the node_modules/@blockly/block-extension-tooltip directory and observe that there is no dist folder

**Expected behavior**
This plugin should be released with a dist directory. The `prepublishOnly` script tag on this plugin generates the dist directory.

**Additional context**

https://docs.npmjs.com/cli/v7/using-npm/scripts

**Comment by maribethb** [comment]
Related to #1123 and now fixed.
