### ISSUE TITLE
Github Pages for third party Blockly Plugins

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#794]
**Category**

Plugins

**Component**

create-package

**Is your feature request related to a problem? Please describe.**

From Noah Glaser on the forum:

> I just added a [GitHub page](https://electroblocks.github.io/blockly-field-color-wheel/index.html) for my Blockly Color Wheel Field.  I created a [ghpages.js](https://github.com/ElectroBlocks/blockly-field-color-wheel/blob/main/ghpages.js) file to compile it and an extra [index.html](https://github.com/ElectroBlocks/blockly-field-color-wheel/blob/main/index.html) file.  It would be cool if  @blockly/create-package code had this functionality out of the box.   No pressure, though, because it was not to get things working. 

**Describe the solution you'd like**
Either add a similar script to create-package, or just add documentation to show how to use the existing ones we have for our own gh-pages.

**Comment by rachel-fenichel** [comment]
@phptuts fyi

**Comment by gonfunko** [comment]
We're now including third-party plugins directly on our [page listing plugins](https://google.github.io/blockly-samples/); rather than having the tooling set up separate pages for third party plugins, we'd encourage developers to reach out to have your plugin included in our main plugin directory.
