### ISSUE TITLE
Recent releases of some plugins are missing dist directory

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#804]
**Category**
Plugins

**Component**
Affected plugins:
- dev-tools
- field-slider
- fixed-edges

**Describe the bug**
The compressed files in the `dist/` directory should be generated by the [`"prepublishOnly"` script](https://docs.npmjs.com/cli/v7/using-npm/scripts) which is meant to be triggered during the `npm run publish` step.
However, some plugins are missing the `dist/` directory in recent releases.

**To Reproduce**

1. View published plugins at:
- https://unpkg.com/browse/@blockly/dev-tools/ [missing dist for the latest release]
- https://unpkg.com/browse/@blockly/field-slider/  [missing dist for the last 2 releases]
- https://unpkg.com/browse/@blockly/fixed-edges/ [missing dist for the last 2 releases]
2. Observe how recent versions are missing the `dist/` directory.

**Expected behavior**
There should always be a `dist/` directory.

**Additional context**
This bug impacts anyone that uses unpkg as they are unable to reference the compressed files in the `dist/` directory because it's not uploaded.

A similar bug was filed for block-extension-tooptip, which has not had it's `dist/` directory included in any of it's releases.
https://github.com/google/blockly-samples/issues/793

**Comment by moniika** [comment]
Possibly fixed by: https://github.com/google/blockly-samples/pull/803
Fix can be confirmed after publishing.

**Comment by BeksOmega** [comment]
@moniika is this good to close?
