### ISSUE TITLE
Add option to not allow Backpack to be openable if it is empty 

### ISSUE THREAD

**Issue by moniika** [RaspberryPiFoundation/blockly-samples#811]
**Category**
Plugins

**Component**
@blockly/workspace-backpack

**Is your feature request related to a problem? Please describe.**
The default behavior of the Backpack is to always allow it to be opened, controlled by the protected method [`isOpenable_`](https://github.com/google/blockly-samples/blob/fb16a806ce44aeb5296647f77bbc5813c3b5ed93/plugins/workspace-backpack/src/backpack.js#L580).
Depending on when the Backpack content update is triggered (as long as it is not triggered on open), it is probably not desired for the Backpack to open and changing this requires subclassing.

**Describe the solution you'd like**
Allow passing in an option to configure whether the Backpack is openable when it is empty, leaving the default behavior to be that it can always open if it is not already open.

**Describe alternatives you've considered**
Leave as is and add additional documentation on how to subclass the Backpack to achieve this.

**Additional context**
The README of the Backpack should also be updated to document this new option in the [Configuration](https://github.com/google/blockly-samples/blob/fb16a806ce44aeb5296647f77bbc5813c3b5ed93/plugins/workspace-backpack/src/backpack.js#L580) section.

**Comment by Chappie74** [comment]
Created a [PR](https://github.com/google/blockly-samples/pull/932) for this.
