### ISSUE TITLE
Add an option to create a 1st party plugin

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#815]
**Category**

Plugins
**Component**
dev-tools

**Is your feature request related to a problem? Please describe.**
When releasing there are certain fields that need to be filled out properly. In the past filling out these fields improperly has caused problems during a release.

**Describe the solution you'd like**
We would like the dev-create script to allow us to specify that we want to create a first party plugin.

Something like: 
```
npx @blockly/create-package my-plugin --type plugin --first-party
```

When creating a first party plugin we would: 
- Precede the plugin name with '@blockly/'
- Fill out the `publishConfig` field with
```
    "publishConfig": {
        "access": "public",
        "registry": "https://wombat-dressing-room.appspot.com"
    },
```
- Fill out the `homepage` field
- Fill out the `repository` field
- Possibly add the plugin to the [gh-pages index.md](https://github.com/google/blockly-samples/blob/master/gh-pages/index.md)

**Describe alternatives you've considered**

**Additional context**

**Comment by maribethb** [comment]
I completed this some time ago, you can pass an option now
