### ISSUE TITLE
small tutorial error

### ISSUE THREAD

**Issue by joecabezas** [RaspberryPiFoundation/blockly-samples#821]
on
https://blocklycodelabs.dev/codelabs/custom-generator/index.html?index=..%2F..index#1

says to use this snippet:
```
<script src="custom_generator.js"></script>
```

but it shall be:
```
<script src="./custom_generator.js"></script>
```

**Comment by gonfunko** [comment]
Thanks for flagging this! Although the codelab does work as written, this would indeed be more consistent with the other script tags in the file. We'd be happy to accept a PR fixing this - I think it would just involve editing https://github.com/google/blockly-samples/blob/master/codelabs/custom_generator/custom_generator.md.
