### ISSUE TITLE
Update debug renderer for Q3 2021 core release

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#826]
The debug renderer defined in the `dev-tools` package relies on the constant provider having created a debug filter during `createDom`. 

In [this commit](https://github.com/google/blockly/pull/5204/commits/046636547ef5e31ea7db352509248a9ccb500fc1) in core I added a function `createDebugFilter`, but am still calling it from in `createDom`. It should only be created when the debugger is in use, so that call should come from outside of core.

Steps to fix:
- Update core to make `createDebugFilter` public and get rid of the call to it in `createDom`
- Update the debug renderer to call `constantsProvider.createDebugFilter` in the constructor
- Publish the change to the debugger after the next publish of core

**Comment by rachel-fenichel** [comment]
Another option in core is to expose an `addDef` call on the constants provider, rather than exposing just `createDebugFilter`. That may be a better API--I held off on it since we're in the middle of goog.module work and I wanted to make a minimal change.

**Comment by BeksOmega** [comment]
@rachel-fenichel did this happen?

**Comment by rachel-fenichel** [comment]
Solved by deleting it.
