### ISSUE TITLE
Provide an example of custom Blockly generator bundled in a ES6 module

### ISSUE THREAD

**Issue by lypwig** [RaspberryPiFoundation/blockly-samples#830]
**Category**

- Examples

**Component**

A new project in the `examples` folder, that includes a custom Blockly generator as a ES6 module ready to be published on npm.

**Is your feature request related to a problem? Please describe.**

I am having trouble to create a simple ES6 module of a Blockly generator.

**Describe the solution you'd like**

I would like an MVP of a Blockly generator as a ES6 module, that can be used with `import 'my-generator';` just like we do with `import 'blockly/python';`.

This example folder will probably include a gulp script that produces the ES6 module, similarly to [blockly's gulp package tasks](https://github.com/google/blockly/blob/master/scripts/gulpfiles/package_tasks.js#L263).

The purpose is not to learn how to write a custom generator, but to understand how to bundle a custom generator to a ES6 module. The custom generator used in the example could be for instance the [json generator used in codelabs](https://blocklycodelabs.dev/codelabs/custom-generator/index.html).

**Comment by maribethb** [comment]
The new Generator codelab uses the sample app template, which uses es6 modules, so I'm going to go ahead and close this as completed. I'd like to note that there is nothing really special about generators that would make exporting a generator as an es6 module different from any other module, so if you have further questions about this topic you may wish to ask on the forum for more clarification. Thanks!
