### ISSUE TITLE
content-highlight dispose throws error

### ISSUE THREAD

**Issue by BeksOmega** [RaspberryPiFoundation/blockly-samples#831]
**Category**

 - Plugins

**Component**

content-highlight

**Describe the bug**

When you call dispose() it throws an error because the `Blockly.unbindEvent_` call is incorrect.

**To Reproduce**

1. Add a `dispose` call immediately after the init call [here](https://github.com/google/blockly-samples/blob/361935c17188ca1ecb3fea863cb65b47859007e8/plugins/content-highlight/test/index.js#L25).
2. `npm run start`
3. Observe the error in the console

**Expected behavior**

No Errors

**Additional context**
I think it should call `workspace.removeChangeListener` rather than `Blockly.unbindEvent_`
Reported in this forum post: https://groups.google.com/g/blockly/c/kV7UZ0lAD0A

**Comment by nishit-prasad** [comment]
Hello, I am new and would like to work on this if it's available?
Would probably need direction on setup to make sure I have everything set.

**Comment by SebCanet** [comment]
@BeksOmega I tried what you propose, now there is no error message, but plugin is still functionning.
I tried to change `Blockly.unbindEvent_(this.onChangeWrapper_);` by `Blockly.browserEvents.unbind(this.onChangeWrapper_);` and also by `this.workspace_.removeChangeListener(this.onChangeWrapper_);`, but no effect...
If someone can have a solution...thanks.

**Comment by BeksOmega** [comment]
> @BeksOmega I tried what you propose, now there is no error message, but plugin is still functionning. I tried to change `Blockly.unbindEvent_(this.onChangeWrapper_);` by `Blockly.browserEvents.unbind(this.onChangeWrapper_);` and also by `this.workspace_.removeChangeListener(this.onChangeWrapper_);`, but no effect... If someone can have a solution...thanks.

Could you describe how the plugin is still not functioning? The more information we have the easier it is to debug problems =)

**Comment by SebCanet** [comment]
Maybe I misundertand the dispose() command... Normally if I call this function, the plugin should unregister itslef and the workspace should come back to 'normal' state (white workspace). It's like a switch on/off for the plugin: switch init/dispose.

**Comment by maribethb** [comment]
Changing the line from `Blockly.unbindEvent_(this.onChangeWrapper_);` to `this.workspace_.removeChangeListener(this.onChangeWrapper_);` and then calling `contentHighlight.dispose();` worked perfectly for me. There is no error and the plugin is correctly disposed/disabled. The highlight disappears and does not come back after adding new blocks.

If that's not the behavior you see then we would need more information.

**Comment by SebCanet** [comment]
Sorry, it works now, with your help. I don't understand why I had bugs...
Maybe you can valid this patch and close this issue?
Many thanks.
