### ISSUE TITLE
Set up auto-assignment for changes in this repository

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#848]
This can be done with a [CODEOWNERS](https://github.com/google/blockly/blob/develop/.github/CODEOWNERS) file. However, for this repository we may want more specific owners for individual folders.

**Comment by alschmiedt** [comment]
When we add this we should also looking at pulling over the [assign reviewer GitHub action](https://github.com/google/blockly/blob/master/.github/workflows/assign_reviewers.yml) that we added in core.

**Comment by alschmiedt** [comment]
Fixed in #1046
