### ISSUE TITLE
Add a linter to check conventional commits

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#880]
We want to start using [release please ](https://github.com/googleapis/release-please)in q4 2021. In order to do this we need to make sure we are using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) properly. 

Add a [conventional commit](https://github.com/googleapis/repo-automation-bots/tree/main/packages/conventional-commit-lint) linter to check that all incoming commits are formatted properly.

**Comment by rachel-fenichel** [comment]
Done.
